In [ ]:
import torch
import numpy as np
import pandas as pd

## Introduction to tensors

### Creating tensors

https://pytorch.org/docs/stable/tensors.html

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as python int
scalar.item()

7

In [ ]:
# vector
vector = torch.tensor([[1],
                       [1]])
print(vector)
print(vector.ndim) # number of closing square brackets
print(vector.shape)

tensor([[1],
        [1]])
2
torch.Size([2, 1])


In [ ]:
# MATRIX

MATRIX = torch.tensor([[12,34],
                       [65,98]])
print(MATRIX)
print(MATRIX.ndim) # number of closing square brackets
print(MATRIX.shape)

tensor([[12, 34],
        [65, 98]])
2
torch.Size([2, 2])


In [ ]:
MATRIX[0]

tensor([12, 34])

In [ ]:
MATRIX[1]

tensor([65, 98])

In [ ]:
MATRIX[1:]

tensor([[65, 98]])

In [ ]:
#TENSOR

TENSOR = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
print(TENSOR)
print(TENSOR.ndim) # number of closing square brackets
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])


In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR[0,1:,1:]

tensor([[5, 6],
        [8, 9]])

## Random Tensors

###Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random nimbers to better represent the data.

`Start with random numbers -> look at the data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3752, 0.4672, 0.8326, 0.8717],
        [0.0741, 0.8380, 0.2055, 0.6313],
        [0.7680, 0.2419, 0.8958, 0.6862]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Creste a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(3,224, 224) # height , weight , colour channels (r , b , g)
print(random_image_size_tensor)
print(random_image_size_tensor.ndim) # number of closing square brackets
print(random_image_size_tensor.shape)

tensor([[[0.3865, 0.9073, 0.6773,  ..., 0.7930, 0.3547, 0.3890],
         [0.0376, 0.3937, 0.6575,  ..., 0.9037, 0.1340, 0.1599],
         [0.3730, 0.5938, 0.5286,  ..., 0.3506, 0.0355, 0.3519],
         ...,
         [0.9997, 0.4574, 0.7704,  ..., 0.3814, 0.5310, 0.6657],
         [0.6876, 0.0756, 0.6104,  ..., 0.9684, 0.7682, 0.7545],
         [0.3093, 0.2817, 0.5810,  ..., 0.9296, 0.2537, 0.0334]],

        [[0.5805, 0.2687, 0.4328,  ..., 0.7711, 0.2490, 0.1159],
         [0.9875, 0.2344, 0.6685,  ..., 0.3903, 0.1472, 0.9160],
         [0.9946, 0.0869, 0.2618,  ..., 0.3837, 0.7831, 0.5362],
         ...,
         [0.7124, 0.6188, 0.6102,  ..., 0.4510, 0.3235, 0.9097],
         [0.4542, 0.0019, 0.2371,  ..., 0.4914, 0.9224, 0.4191],
         [0.8226, 0.0773, 0.9811,  ..., 0.8205, 0.5639, 0.0952]],

        [[0.8121, 0.3756, 0.7080,  ..., 0.9291, 0.0364, 0.7206],
         [0.2485, 0.5522, 0.7420,  ..., 0.7018, 0.7461, 0.3480],
         [0.8148, 0.3399, 0.9021,  ..., 0.2480, 0.0763, 0.

### Zeros and ones

In [ ]:
# create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensor likes

In [ ]:
one_to_ten = torch.arange(1,11)

In [ ]:
torch.arange(start=0 , end=10000 , step=88)

tensor([   0,   88,  176,  264,  352,  440,  528,  616,  704,  792,  880,  968,
        1056, 1144, 1232, 1320, 1408, 1496, 1584, 1672, 1760, 1848, 1936, 2024,
        2112, 2200, 2288, 2376, 2464, 2552, 2640, 2728, 2816, 2904, 2992, 3080,
        3168, 3256, 3344, 3432, 3520, 3608, 3696, 3784, 3872, 3960, 4048, 4136,
        4224, 4312, 4400, 4488, 4576, 4664, 4752, 4840, 4928, 5016, 5104, 5192,
        5280, 5368, 5456, 5544, 5632, 5720, 5808, 5896, 5984, 6072, 6160, 6248,
        6336, 6424, 6512, 6600, 6688, 6776, 6864, 6952, 7040, 7128, 7216, 7304,
        7392, 7480, 7568, 7656, 7744, 7832, 7920, 8008, 8096, 8184, 8272, 8360,
        8448, 8536, 8624, 8712, 8800, 8888, 8976, 9064, 9152, 9240, 9328, 9416,
        9504, 9592, 9680, 9768, 9856, 9944])

In [ ]:
# creating tensor like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

If only int given default dtype is int64
if given with decimal default dtype is float32

float32 is single decimal precision number , eg 3.5 , 4.6 etc

**Note:** Tensor dtypes is one of the 3 big errors with pytorch & deep learning

1. Tensors not right dtype
2. Tensor not right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.54,766.45,9.3254])
float_32_tensor

tensor([  3.5400, 766.4500,   9.3254])

In [ ]:
float_32_tensor.device

device(type='cpu')

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
a = torch.tensor([3.,6.,9.], dtype = torch.float16, # defines dtype of the tensor
                            device = cuda ,  # device where computataion takes place cpu , gpu or tpu
                            requires_grad = None ) # whether or not to track gradients with this tensor operations

NameError: ignored

In [ ]:
a.dtype

NameError: ignored

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([  3.5391, 766.5000,   9.3281], dtype=torch.float16)

In [ ]:
float_16_tensor.dtype

torch.float16

In [ ]:
float_32_tensor * float_16_tensor

tensor([1.2528e+01, 5.8748e+05, 8.6989e+01])

In [ ]:
int_tensor = torch.tensor([3,4,5])

In [ ]:
float_32_tensor * int_tensor

tensor([  10.6200, 3065.8000,   46.6270])

From above 2 code cells we can see that torch is robust to dtype error on math opertaions , but not necesserily eveytime , at some point it will give dtype error , at that point we should know how to change dtype

### Getting information form tensors

1. Tensors not right dtype - to get dtype - `tensor.dtype`
2. Tensors not right shape - to get shape - `tensor.shape`
3. Tensors not right device - to get device - `tensor.device`

### Manipulating tensors ( tensor operations )

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element - wise)
* Division
* Matrix Multiplication

In [ ]:
# create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
#Multiply with 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
 # try out inbuilt torch function
 torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match
*  `(3,2) @ (3,2)` won't work
*  `(2,3) @ (3,2)` will work
*  `(3,2) @ (3,2)` will work
2. The resulting matrix has the shape of the **outer dimensions**.
*  `(2,3) @ (3,2)` -> `(2,2)`
*  `(3,2) @ (3,2)` -> `(3,3)`


In [ ]:
# Element wise multiplication

print(tensor ,"*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 277 µs, sys: 28 µs, total: 305 µs
Wall time: 314 µs


tensor(14)

In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 77 µs, sys: 8 µs, total: 85 µs
Wall time: 90.6 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[11,12],
                         [13,14],
                         [15,16]])

# torch.mm(tensor_A,tensor_B) # torch.mm is the same as tprch.matmul (it's an alias for matmul)
torch.mm(tensor_A,tensor_B)

RuntimeError: ignored

In [ ]:
tensor_A.shape , tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix out tensor shape issues , we can manipulate the shape of one of our tensors using torch.transpose

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B.T

tensor([[11, 13, 15],
        [12, 14, 16]])

In [ ]:
tensor_B

tensor([[11, 12],
        [13, 14],
        [15, 16]])

In [ ]:
tensor_B.T.shape , tensor_B.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [ ]:
torch.mm(tensor_A,tensor_B.T), torch.mm(tensor_A,tensor_B.T).shape

(tensor([[ 35,  41,  47],
         [ 81,  95, 109],
         [127, 149, 171]]),
 torch.Size([3, 3]))

### Finding the min , max , mean , summ , etc (tensor aggregation)

In [ ]:
# Create a tensor

x = torch.arange(0,50,4)
x , x.dtype

(tensor([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48]), torch.int64)

In [ ]:
# Find the mean
torch.min((x)) , x.min()

(tensor(0), tensor(0))

In [ ]:
# Find max
torch.max((x)) , x.max()

(tensor(48), tensor(48))

#### Torch.mean() requires the dtype to be float32

In [ ]:
torch.mean(x.type(torch.float32))

tensor(24.)

In [ ]:
x = x.type(torch.float32)

In [ ]:
x.type(torch.float32).mean()

tensor(24.)

In [ ]:
# Find mean
torch.mean(x)

tensor(24.)

In [ ]:
# To get index  of max in tensor
torch.argmax(x)

tensor(12)

In [ ]:
# To get index  of min in tensor
torch.argmin(x)

tensor(0)

## Reshaping stacking and squeezing and unsqueezing tensors



*   Reshaping - reshapes an input tensor to define shape
*   View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
*   Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
*   Squeeze - remove all `1` dimensions from a tensor
*   Unsqeeze - add a `1` dimension to a target tensor
*   Permute - return a view of the input with dimensions permuted (swapped) in a certain way








In [ ]:
# create a tensor
import torch

x = torch.arange(1.,11.)
x , x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1,7)

RuntimeError: ignored

In [ ]:
x_reshaped = x.reshape(1,10) # adds a pair of single squaere brackets on the outside
x_reshaped , x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
x_reshaped = x.reshape(2,10)
x_reshaped , x_reshaped.shape # requires 18 elements

RuntimeError: ignored

In [ ]:
x_reshaped = x.reshape(10,1) # adds a pair of single squaere brackets on the inside
x_reshaped , x_reshaped.shape

(tensor([[ 5.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [ ]:
x_reshaped1 = x.reshape(2,5)
x_reshaped2 = x.reshape(5,2)  # requires 10 elements
x_reshaped1 , x_reshaped1.shape ,x_reshaped2 , x_reshaped2.shape

(tensor([[ 5.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]),
 tensor([[ 5.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [ ]:
# Change the view
z = x.view(1,10)
z , z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z , x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = -2) # hstack is dim = 0 , vstack is dim = 1
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [ ]:
# torch.squeeze - removes all single dimenstions from a target tensor
x_reshaped , x_reshaped.shape

(tensor([[ 5.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [ ]:
x_squeezed = x_reshaped.squeeze()
x_squeezed ,  x_squeezed.shape

(tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
#torch.insqueeze() - adds a single dimensionto a target tensor at a specific dim (dimension)
print(f"Previous target : {x_squeezed}")
print(f"Previous shape : {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor : {x_unsqueezed}")
print(f"new shape : {x_unsqueezed.shape}")

###Pytorch tensors and numpy

Numpy is a scientific python numerical computer library

And because of this, pytorch has functionality to interact with it.



*   Data in numpy array, want a pytorch tensor -> `torch.from_numpy(ndarray)`
*   pytorch tensor to numpy array -> `torch.tensor.numpy()`



In [ ]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # warning when converting from numpy to pytorch, pytorch reflects numpy 's default datatype of float64 unless specified otherwise
array , tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
tensor.dtype

torch.float64

In [ ]:
torch.arange(1.0,8.0).dtype

torch.float32

In [ ]:
tensor = torch.from_numpy(array,dtype=torch.float32)

TypeError: ignored

In [ ]:
tensor.type(torch.float32)

tensor([1., 2., 3., 4., 5., 6., 7.])

In [ ]:
# Change the value of array
#array = array + 1
tensor1 = torch.from_numpy(array)
array , tensor1 , tensor

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to numpy array
tensor = torch.ones(7)
np_tensor = tensor.numpy()
tensor , np_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
np_tensor.dtype

dtype('float32')

**Note:**

*   When going from nparray to tensor we get default dtype to be `torch.float64`
*   When going from tensor to nparray we get default dtype to be `float32`



In [ ]:
# change the tensor , whats happens to numpy_tensor

tensor = tensor + 1
np_tensor1 = tensor.numpy()
tensor , np_tensor, np_tensor1

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

### Reproducibility (trying to take random out of random)

In short how a neural network learns:

`starts with random numbers -> tensor operations -> update numbers to try and make them better representation of the data -> again -> again -> again ....`

To reduce the randomness in neural networks and pytorch comes the concept of **random seed.**

Essentially what the random seed does is flavour the randomness.


In [ ]:
import torch

In [ ]:
torch.rand(3,3)

tensor([[0.3383, 0.8029, 0.9690],
        [0.4786, 0.2098, 0.2450],
        [0.8130, 0.8358, 0.4647]])

In [ ]:
# create 2 random tensors
rand_ten_A = torch.rand(3,4)
rand_ten_B = torch.rand(3,4)

print(rand_ten_A)
print(rand_ten_B)
print(rand_ten_A == rand_ten_B)

tensor([[0.3899, 0.6385, 0.9818, 0.3412],
        [0.4929, 0.1301, 0.9568, 0.7318],
        [0.4964, 0.0155, 0.2976, 0.1336]])
tensor([[0.6842, 0.5514, 0.0167, 0.7690],
        [0.4674, 0.0922, 0.6523, 0.2753],
        [0.2599, 0.8555, 0.7105, 0.0586]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# let's make some random but reproducible tensor

# Set random tensor seed
RANDOM_SEED  = 0

torch.manual_seed(RANDOM_SEED)
rand_ten_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
rand_ten_D = torch.rand(3,4)

print(rand_ten_C)
print(rand_ten_D)
print(rand_ten_C == rand_ten_D)

tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors or PyTorch objects on the GPU's (and making faster computauions)

GPUs = faster computatuion on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory(good).   

In [1]:
!nvidia-smi

Wed Jun 28 09:53:47 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
### 1. Check for GPU access with PyTorch

import torch
torch.cuda.is_available()

True

In [3]:
# Steup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# Count number of devices
torch.cuda.device_count()

1

**Best practices while using GPU with PyTorch**

https://pytorch.org/docs/stable/notes/cuda.html

## 2. Putting tensors (and models) on the GPU

In [5]:
# Crate a tensor (deafult on CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [10]:
# Move tensor to GPU (if available)
tensor_on_gpu1 = tensor.to(device)
tensor_on_gpu1

tensor([1, 2, 3], device='cuda:0')

In [ ]:
## 3. Moving tensors back to CPU

In [9]:
tensor_on_cpu = tensor.to(device='cpu')
tensor_on_cpu,tensor_on_cpu.device

(tensor([1, 2, 3]), device(type='cpu'))

In [12]:
# If tensor id on GPU , can't transform it ti NumPy
tensor_on_gpu1.numpy()

TypeError: ignored

**Tensors on gpu cant be converted to numpy array , first get them back to cpu then we can use numpy**

In [13]:
tensor_on_cpu.numpy()

array([1, 2, 3])

In [14]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [15]:
del tensor_on_gpu

In [16]:
!nvidia-smi

Wed Jun 28 10:12:54 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   55C    P0    29W /  70W |    601MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------